/********************* list o prototypes *************/
#include "RealmzCocoa.h"
#include "files.h"

void showtag(Str255 message, short data1, short data2);
void showdamage(short body, short how, short damage);
void loaditemnotype(short id);
void updatemonstermenu(short currentload);
void centercursor(void);
void order(void);
short direction(float dx, float dy);
void spellinfoupdate(void);
short seeshop(short mode);
void loaddark(short lightlevel);
// short abs(short);
void GetVersStr(short id, short refnum);
void loadland(long id, short mode);
void compactheap(void);
short actionpicker(void);
short age(long age, short raceid, short currentagegroup);
void showageupdate(short who, short agegroup, short backup);
void applyage(short raceid, short agegroup, short direction);
short attack(short chare, short mon);
short attack2(short mon, short chare, short attacknum);
void beast(short who, short mode, short specific);
void bodycount(void);
void bodyground(short body, short where);
void monsterupdate(short who, Rect where);
void updatenpcmenu(void);
void bodyfield(short mon);
void updatebootymoney(Rect icon, Rect swapicon);
void booty(short mode);
void updateshop(void);
void eraseshopstats(short mode);
void eraseshopname(short mode);
void shortupdate(short mode);
void selectupdate(void);
void center(short mon);
void in(void);
void out(void);
void downbutton(short newport);
void checkfordoauto(void);
short doreg(void);
void DialogNumNZ(short theItem, short theNum);
void buildmonster(short traiter);
short buttonchoice(short skipin);
short cansee(short fromx, short fromy, short tox, short toy);
short cansee2(long fromx, long fromy);
short castspell(void);
void showspelllist(void);
void updatetier(short mode);
void cast(short targetnum, short who);
void centerfield(short x, short y);
void centerpict(void);
void centerstage(short way);
void change(short play, short mode);
short checkforenemy(short code);
short checkforsecret(short force);
short checkfortype(short who, short type, short aliveonly);
short checklayout(long currentlevel);
short checkkeypad(short mode);
void checkmoneypool(void);
short checkrange(short body, short targetx, short targety);
short checkforitem(short id, short usecharge, short who);
short checkforcharge(short id);
short choice(short key);
void Caste(short mode);
void collide(short who, short checkcontrol);
void combat(short suprise, short mode);
void combaterrors(short error);
void combatinfo(short tempold);
short checkdelay(short scale);
void combatchoice(void);
void combatmap(void);
short combatsetup(short mode, short suprise, short combatmode);
void combatupdate(short body);
void combatupdate2(short body);
void compactitems(short who);
void showcontactinfo(void);
void showcontact(void);
short loadcontact(void);
void delay(short timedelay);
void destroymonster(short tt);
void Display(short mode);
void drawbody(short body, short force, short where);
void dropitem(short who, short itemid, short itemnum, short dropsound, short force);
OSErr SetIndString(StringPtr theStr, short resID, short strIndex);
void editspellnames(void);
void editracecaste(void);
void downbutton2(void);
void makestring(short id);
void getstring(void);
void warp(void);
void editstring(void);
void emptyque(void);
short thiefenc(void);
short encounter(short id, short mode);
short encounter2(void);
void fastplot(short id, Rect destrect, short mode, short where);
short fileprep(short mode);
void flashrange(short which, short who);
void loaddoor(long id, short index);
void loaddoor2(short id);
void flashmessage(Str255 string, short x, short y, short duration, short toplay);
void getbattleorder(short suprise);
short getchoice(short number, short initems, short candead);
short getnumspells(short spellcastertype, short casteid, short level);
short getrange(short body, short side, short flip);
short getscroll(void);
short getselection(short tempid);
void getup(short skip);
void GetVersStr(short id, short refnum);
void getword(void);
void Gender(void);
void GWorldInit(void);
short HandleMenuChoice(void);
void heal(short who, short howmuch, short show);
void iconpicture(short mode);
short inwindow(short who);
short items(void);
void killbody(short mon, short performque);
short levelup(short character, short mode);
short load(void);
void loadshop(short mode);
void saveshop(short mode, char filename[256]);
void loaditem(short id);
void loadland(long id, short mode);
void loadpixmap(short id);
void loadspell2(short id);
void loadspell(short castcaste, short castlevel, short castnum);
short lookupicon(short iconid, short ident);
void updatecompass(void);
void UpdateWindow(short titleonly);
void SetViewVariables(void);
void makescroll(void);
void fastplotmap(short id, Rect destrect);
void showmap(short mapnumber);
void MenuInit(void);
short doreg5(void);
short doreg4(void);
short regscen(void);
short regscen_pc(void); // Fantasoft v7.1
short regscen_pc_custom(void); // Fantasoft v7.1
void drawspell(void);
void movecalc(short charselect);
void mainscreeninit(short mode, short dostart);
void getexp(short level, short casteid, short who);
void cleartarget(void);
void pict(short id, Rect frame);
void string(short number);
void loadextracode(short id);
short tween(short tween, short left, short right);
short twixt(short tween, short left, short right);
short randrange(short low, short high);
void updateprep(void);
void strength(short st);
void getcharrange(short body);
long GetDialogNum(short number);
void xy(short mode);
void scratch(short location);
void scratch2(short location);
void savecharacter(short who);
void setfileinfo(char type[4], char filename[256]);
void calcw(short who);
pascal void ScrollProc(ControlHandle dummycontrol, short theCode);
short editportraits(short fromid, short mode);
void shortupdate(short mode);
void selectupdate(void);
void center(short mon);
short savevs(short which, short who);
short savevsattr(short which, short who);
void adddelscen(short mode);
void getfilename(char tempfilename[256]);
void copyresource(short fromrefnum, short torefnum, ResType res_type, short toid, short fromid);
void quitgame(void);
void removeresource(short fromrefnum, ResType res_type, short fromid);
void loadprofile(short raceid, short casteid);
void bandaid(void);
void setverify(short who);
short checkverify(short who);
void updatemapmenu(void);
short Startlevel(void);
void memout(void);
void quiet(short id);
void updatemusic(void);
void sound(short id);
void updatemain(short center, short who);
void mainscreen(short who);
void openrace(void);
void opencaste(void);
short usercheck2(void);
void getdivineuser(void);
void updatescenarioavail(void);
short selectscenario(char tempfilename[256], short mode);
void modify(short mode);
short cancast(short who, short silentmode);
void itemcost(short mode);
void moveicon(void);
short movemonster(void);
void moveparty(short forward);
void movie(short textID, short dataid, short justify);
void music(short playlist);
short Name(short mode);
short pin(short data, short low, short high);
void addinitialitems(void);
void NewCharacter(short level);
void HandleEvent(void);
void CharacterGen(void);
short newland(long x, long y, short mode, short modecode, short data);
void number(void);
short doreg3(void);
void Copy_Part_Of_String(Str255 dst, Str255 src, short start_char, short end_char);
void printstat(short dlog_item, short text_y);
void orderform(void);
void partyselect(short mode);
void viewrestrictions(void);
void partyloss(short mode);
void placemonster(short x, short y, short monsterup);
void ploticon2(short tempid);
void ploticon3(short tempid, Rect therect);
void ploticon(short tempid, short showcurse);
void updateport(void);
void plotportrait(short tempid, Rect where, short class, short who);
void plus(char charactername[30], short level);
void minus(char name[30], short mode);
void pool(void);
void portrait(short mode);
short picklock(short who, short type);
void getappname(void);
void quickinfo(int who, int itemnumber, int itemid, int where);
void savepref(void);
void getpref(void);
short checkformismatch(void);
short createpref(FSSpec pref_FSSpec, short mode);
short openpref(short mode);
void preference(void);
short question(short stringnum);
short question2(short prompt1, short prompt2);
short question3(Str255 prompt1, Str255 prompt2);
void Race(short mode);
void reduce(void);
short removeitem(short character, short itemnum, short play, short force);
short resist(short who);
void resolvespell(void);
void save(short mode);
void saveland(long id);
void saveencounter(short id, short type);
void setfree(long templong);
void setfree2(short force);
void setupnewgame(void);
void share(void);
short Rand(short range);
void DialogNumLong(short theItem, long theNum);
void DialogNum(short theItem, short theNum);
void MyrPascalDiStr(short theItem, Str255 thestring);
void MyrCDiStr(short theItem, Str255 thestring);
void MyrNumToString(long value, Str255 thestring);

short getmovecost(short hit);
void shift(short curx, short cury, short target);
short regdiv(void);
void aboutrealmz(void);
void showcharge2(short charge, short ident);
short showcondition(short start, short stop, short type, short showonly, short who);
short popupchoice(short stringid);
void showcondition2(short who, short type);
void Showitems(short mode);
void showitemstats(short ident);
void showspecial(void);
short canuse(short itemid, short raceid, short casteid);
short showiteminfo(short id, short ident, short charge, short showcurse);
void showlogo(short howlong);
void delay2(short timedelay);
void hideMenuBar(void);
void showMenuBar(void);
void showque(void);
void showrange(short edgemode);
void showresults(short tar, short special, short from);
void showspellinfo(void);
void ShowStats(short showprestige);
void showtargets(short where);
void Spellselect(void);
void spelleffect(short t, short mode);
short spelllist(short who, short special);
short spelltargets(short targetnum, short who, short mode, short noreflect);
void swap(void);
short takegold(short gold, short type);
void temple(void);
void textbox(short class, short index, short click, short different, Rect newrect);
short timeclick(unsigned char number, short checkforrandom);
void threed(long id, short gox, short goy, short dir);
void Render(void);
void updatewalls(long x, long y);
void plotwall(short id);
void tickcheck(void);
void updatetorch(void);
void upbutton(short newport);
void finddxdy(short from, short to);
short toweap(short who);
short tomissle(short who);
void missileset(float dx, float dy);
void updatemoney(short mode);
void updatearrow(short mode);
void updatebooty(short charnum);
void updatechar(short who, short mode);
void updatecharinfo(void);
void updatecharshort(short who, short forcebox);
void updatecontrols(void);
void updatefat(short show, short num, short erase);
void updateitems(short top, short bottom);
void updatelight(short who, short offpict);
void updatepictbox(short who, short mode, short noplotmode);
void updateshopwings(int cl, int cr);
void updatespec(short mode);
void updatespell(short force);
void viewcharacter(short view, short mode);
void warn(short string);
short wear(short character, short itemnum, short play);
void ToolBoxInit(void);
int main(int argc, char* argv[]);
void MainLoop(void);
short checkforerrors(void);
void aboutrealmz(void);
void compactheap(void);
void fadeinout(short steps, short fadedirection);
void updatecanlist(void);
void pushonstack(struct door pushdoor, short counter);
short pulloffstack(void);
void MyrDrawCString(Ptr strc);
void RedrawAllRealmz(void);
void DoFreeBeforeQuit(void);

void MyrCopyScreen(CGrafPtr portSource, CGrafPtr portTest, Rect* rectSource, Rect* rectDest, short mode);
void MyrParamText(Ptr p1, Ptr p2, Ptr p3, Ptr p4);
void MyrPreserveScreen(CGrafPtr portDest, Rect* rectSource, Rect* rectDest);
void MyrRestoreScreen(CGrafPtr portDest, Rect* rectSource, Rect* rectDest);
void MyrCopyMask(CGrafPtr portSource, CGrafPtr masque, CGrafPtr portDest, Rect* rectSource, Rect* rectMask, Rect* rectDest);
void MyrScreenToScreen(Rect* rectSource, Rect* rectDest, short mode);
void MyrCopyIconMask(CIconHandle icon, CGrafPtr portDest, Rect* rectDest);
void MyrStrPtoC(char* str);
void MyrAppendMenu(MenuHandle menu, Ptr str);
void MyrStrCtoP(char* str);
// void PauseMadMusic(void);
short MyrRemove(char* nomMac);
short MyrOpenResFile(char* nomMac);
FILE* MyrFopen(char* nomMac, char* type);
void MyrCheckMemory(short mode);
void MyrDump(char* format, ...);
void MyrInitCheckMemory(void);
